### PR TITLE
Update to traefik 2.10

### PR DESCRIPTION
**Pull request by reneleonhardt**
## What does this PR do?

This PR:

- Is based on https://github.com/traefik/mesh/pull/842 and will be rebased before merge
- Update to traefik 2.10
- Update direct dependencies (except k8s.io/api 0.26 because it's a traefik 2.10 requirement )
- Update indirect dependencies (in a separate commit)
- Adds one exclude to golangci-lint
- Updates most versioned docker images
- Updates doc toolchain (except Python and requirements.txt)
- Does not update k3s to 1.25 (to stay in sync with docs)
- Does not add or update servicemeshinterface (one alpha update is available for all APIs)
- Does not add or update coredns (1.10 and 1.11 available)

### How to test it

* I ran integration tests against the "Update k3d to v5.4.4" commit from the v1.4 branch

## Additional Notes

This PR is the preparation to update everything before the traefik 3 release.

### CODE REVIEW

**Comment by ldez** [comment]
Same remarks as https://github.com/traefik/mesh/pull/842#pullrequestreview-1678158139

**Comment by ldez** [comment]
> This PR is the preparation to update everything before the traefik 3 release

Traefik v3 is in beta for now, there is not plan before the GA to update Mesh.

**Comment by ldez** [comment]
This PR should be closed in favor of #842

**Comment by reneleonhardt** [comment]
> > This PR is the preparation to update everything before the traefik 3 release
> 
> Traefik v3 is in beta for now, there is not plan before the GA to update Mesh.

I just saw that v3 is nearing GA and wanted Mesh to contain the latest v2.10 before that.

**Pull request closed without merging**
