### PR TITLE
Update alpine base image to v3.15

### PR DESCRIPTION
**Pull request by chenrui333**
## What does this PR do?

Update base alpine image to v3.15

### CODE REVIEW

**Comment by kevinpollet** [comment]
Hello @chenrui333,

Thanks for your contribution,

To move things forward, can you sign the [Contributor License Agreement](https://cla-assistant.io/traefik/mesh?pullRequest=818)?

**Comment by chenrui333** [comment]
@kevinpollet yeah, just did. Thanks!

**Review by kevinpollet — APPROVED** [review]
Thanks 👍

**Pull request merged**
